# Hybrid Deep learning

Hybrid Deep Learning (Hybrid DL) combines conventional ML and DL methods  to  address complex tasks. It's useful  when dealing with limited data, which aims to  leveraging the strengths of both paradigms.
We can use signature-based detection for known attacks, while  deep learning-based anomaly detection for identifying novel attacks.

In [7]:
# Import necessary libraries
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Generate synthetic data for demonstration purposes
# Replace this with your actual data
data = np.random.rand(1000, 10)
labels = np.random.randint(2, size=1000)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, random_state=42)

# Classical ML model (Logistic Regression)
clf = LogisticRegression()
clf.fit(X_train, y_train)
y_pred_clf = clf.predict(X_test)

# Calculate and print the accuracy of the Logistic Regression model
accuracy_clf = accuracy_score(y_test, y_pred_clf)
print(f'Logistic Regression Accuracy: {accuracy_clf}')
print(y_pred_clf)


Logistic Regression Accuracy: 0.545
[0 0 1 0 1 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 1 0 1 1 0 0 0 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 1 1 1 1 0 0 1 0 0 1 1 0 0 1 1 1 0 1 1 1 1 1 0 0 1 0 1
 0 0 0 0 0 1 1 0 1 0 1 1 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0 1 1 1
 0 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 1 1 1 0 0 0 0 1 0 0 0
 1 1 0 1 0 0 1 0 0 1 1 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 1 1 0
 0 1 1 1 1 0 0 0 1 0 0 1 1 0 1]


Deep learning

In [6]:

# Deep Learning model (Shallow Neural Network using TensorFlow/Keras)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(10,)),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32)

y_pred_dl = (model.predict(X_test) > 0.5).astype(int)

# Calculate and print the accuracy of the DNN model
accuracy_dnn = accuracy_score(y_test, y_pred_dl)
print(f'Deep Neural Network Accuracy: {accuracy_dnn}')
print(y_pred_dl)

Epoch 1/10
25/25 [==============================] - 0s 1ms/step - loss: 0.6967 - accuracy: 0.4938
Epoch 2/10
25/25 [==============================] - 0s 1ms/step - loss: 0.6917 - accuracy: 0.5113
Epoch 3/10
25/25 [==============================] - 0s 1ms/step - loss: 0.6907 - accuracy: 0.5387
Epoch 4/10
25/25 [==============================] - 0s 1ms/step - loss: 0.6901 - accuracy: 0.5475
Epoch 5/10
25/25 [==============================] - 0s 1ms/step - loss: 0.6893 - accuracy: 0.5325
Epoch 6/10
25/25 [==============================] - 0s 1ms/step - loss: 0.6896 - accuracy: 0.5225
Epoch 7/10
25/25 [==============================] - 0s 1ms/step - loss: 0.6877 - accuracy: 0.5525
Epoch 8/10
25/25 [==============================] - 0s 1ms/step - loss: 0.6873 - accuracy: 0.5487
Epoch 9/10
25/25 [==============================] - 0s 1ms/step - loss: 0.6868 - accuracy: 0.5450
Epoch 10/10
7/7 [==============================] - 0s 1ms/step
Deep Neural Network Accuracy: 0.49
[[1]
 [0]
 [0]
 [1]


Hybrid results

In [8]:
# Hybrid approach (Combine predictions from both models)
y_pred_hybrid = np.logical_or(y_pred_clf, y_pred_dl).astype(int)

# Evaluate the hybrid model

#accuracy = accuracy_score(y_test, y_pred_hybrid)
#print(f'Hybrid Model Accuracy: {accuracy}')
print(y_pred_hybrid)


[[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 0 1]
 [0 0 1 ... 1 0 1]
 ...
 [0 0 1 ... 1 0 1]
 [0 0 1 ... 1 0 1]
 [0 0 1 ... 1 0 1]]
