Matrix math follows several rules, including:

1. **Addition and Subtraction**:
   - Matrices can be added or subtracted if they have the same dimensions.
   - Addition or subtraction is performed element-wise.

2. **Scalar Multiplication**:
   - A scalar (single number) can be multiplied by a matrix.
   - Each element of the matrix is multiplied by the scalar.

3. **Matrix Multiplication**:
   - Two matrices can be multiplied if the number of columns in the first matrix equals the number of rows in the second matrix.
   - The resulting matrix has dimensions equal to the number of rows of the first matrix by the number of columns of the second matrix.
   - The elements of the resulting matrix are computed by taking the dot product of rows of the first matrix and columns of the second matrix.

4. **Transposition**:
   - The transpose of a matrix is obtained by swapping its rows and columns.
   - If \( A \) is an \( m \times n \) matrix, then \( A^T \) is an \( n \times m \) matrix.
   - Transposing twice returns the original matrix: \( (A^T)^T = A \).
   
5. **Inverse**:
   - Not all matrices have inverses. A square matrix that does have an inverse is called invertible or nonsingular.
   - The inverse of a matrix \( A \) is denoted as \( A^{-1} \).
   - If \( A \) is an invertible matrix, then \( A \times A^{-1} = A^{-1} \times A = I \), where \( I \) is the identity matrix.
   - The inverse of a matrix can be found using various methods such as Gaussian elimination, LU decomposition, or using numpy's `np.linalg.inv()` function.

These are fundamental rules, and understanding them is crucial for working with matrices effectively in various mathematical and computational contexts.

In [1]:
import numpy as np

In [9]:
import numpy as np

matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8, 9],
                    [10, 11, 12]])

# Perform matrix addition
result = matrix1 + matrix2

print(result)


[[ 8 10 12]
 [14 16 18]]


In [10]:
import numpy as np

# Define the matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

# Perform matrix subtraction
result = matrix1 - matrix2

print(result)


[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [11]:
import numpy as np

# Define the matrices
matrix1 = np.array([[10, 20],
                    [30, 40]])

matrix2 = np.array([[2, 4],
                    [5, 10]])

# Perform element-wise division
result = matrix1 / matrix2

print(result)


[[5. 5.]
 [6. 4.]]


In [12]:
import numpy as np

# Define the matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

# Alternatively, you can use the @ operator:
# result = matrix1 @ matrix2

print(result)


[[ 58  64]
 [139 154]]


Certainly! Let's walk through how the dimensions change during matrix multiplication:

Consider two matrices:

Matrix 1: Shape (2x3)
```
[[1, 2, 3],
 [4, 5, 6]]
```

Matrix 2: Shape (3x2)
```
[[7, 8],
 [9, 10],
 [11, 12]]
```

To perform matrix multiplication, the number of columns in the first matrix must equal the number of rows in the second matrix.

1. **Matrix 1 (2x3) and Matrix 2 (3x2)**:

- The number of columns in Matrix 1 (3) equals the number of rows in Matrix 2 (3), so they can be multiplied.

2. **Resultant Matrix (2x2)**:

- The resulting matrix will have the same number of rows as the first matrix (2) and the same number of columns as the second matrix (2).

Here's how it looks step by step:

1. For the (1,1) element of the result:

```
(1*7) + (2*9) + (3*11) = 7 + 18 + 33 = 58
```

2. For the (1,2) element of the result:

```
(1*8) + (2*10) + (3*12) = 8 + 20 + 36 = 64
```

3. For the (2,1) element of the result:

```
(4*7) + (5*9) + (6*11) = 28 + 45 + 66 = 139
```

4. For the (2,2) element of the result:

```
(4*8) + (5*10) + (6*12) = 32 + 50 + 72 = 154
```

So, the resultant matrix will be:

```
[[58, 64],
 [139, 154]]
```

The dimensions change from (2x3) and (3x2) to (2x2) during the multiplication process.

<h3 style='color:blue'>Calculate profit/loss from revenue and expenses</h3>

each row is a different product , each column is a different senario

In [2]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [3]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

<h3 style='color:blue'>Calculate total sales from units and price per unit using matrix multiplication</h3>

In [5]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

dot product

In [7]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

In [13]:
import numpy as np

# Define a matrix
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Transpose the matrix
A_transpose = A.T

# Alternatively, you can use np.transpose()
# A_transpose = np.transpose(A)

print("Original Matrix:")
print(A)

print("\nTransposed Matrix:")
print(A_transpose)


Original Matrix:
[[1 2 3]
 [4 5 6]]

Transposed Matrix:
[[1 4]
 [2 5]
 [3 6]]


In [14]:
import numpy as np

# Define a matrix
A = np.array([[1, 2],
              [3, 4]])

# Find the inverse of the matrix
A_inv = np.linalg.inv(A)

print("Original Matrix:")
print(A)

print("\nInverse Matrix:")
print(A_inv)


Original Matrix:
[[1 2]
 [3 4]]

Inverse Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [16]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# Multiply A by its inverse
identity_matrix = np.dot(A, A_inv)

print("\nIdentity Matrix:")
print(identity_matrix)



Identity Matrix:
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
